spring:
  application:
    name: movieflix-2

  datasource:
    url: jdbc:postgresql://postgres:5432/movieflix-database
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true