services:
  postgres:
    image: postgres:latest
    container_name: postgres-docker-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: movieflix-database
    ports:
      - '5432:5432'